"""empty message

Revision ID: 5740ef02a7a0
Revises: 37149c24f970
Create Date: 2023-01-24 14:36:22.847058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5740ef02a7a0'
down_revision = '37149c24f970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
