"""empty message

Revision ID: ddf1d081c9e8
Revises: 5740ef02a7a0
Create Date: 2023-01-24 14:38:00.632250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf1d081c9e8'
down_revision = '5740ef02a7a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
